### ISSUE TITLE
360° video support

### ISSUE THREAD

**Issue by bibsp** [VoidXH/Cinema-Shader-Pack#1]
Can you make a shader for MPC-HC for playing 360° videos?

**Comment by Alp1821** [comment]
Is it possible to do? Give some kind of reply at least, or delete this issue.
I don't want it to be kept open unnecessarily.

**Comment by VoidXH** [comment]
It's not possible in shader, it would require registers for mouse input to move around or an exact rotation to watch all video. The first is impossible (there are no such registers - and most are currently bugged in MPC-HC), the second is pointless.
